version: '3.8'

services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=wallet_api
    build:
      context: ./docker
      dockerfile: ./db.dockerfile


  wallet-api:
    container_name: wallet-api
    build:
      context: .
      dockerfile: ./docker/app.dockefile
    volumes:
      - .:/wallet-api
    command: uvicorn rest.server:app --reload --workers 1 --host 0.0.0.0 --port 8080
#    env_file:
#      - ./env
    ports:
      - 8080:8080
    depends_on:
      - postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
